FROM debian:stable-slim
RUN apt-get update && apt-get install -y curl libssl-dev && rm -rf /var/lib/apt/lists/*

RUN  addgroup --gid 1000 runner && \
    adduser --uid 1000 --home /data --ingroup runner --disabled-password runner

USER runner

VOLUME /data
WORKDIR /data

EXPOSE 4000/tcp
COPY hykey ./
CMD ["./hykey"]