version: "3.9"

services:
  dragonfly:
    # the new redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    command:
      - "--save_schedule=*:*" # save for every 1 minute
      - "--dir=/data"
      - "--dbfilename=dump.rdb"
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - "./dragonfly_data:/data"
    restart: unless-stopped
networks:
  redis:
    driver: bridge
