version: "3.9"

services:
  dragonfly:
    # the new redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    command:
      - "--save_schedule=*:*" # save for every 1 minute
      - "--dir=/data"
      - "--dbfilename=dump.rdb"
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - "./dragonfly_data:/data"
    restart: unless-stopped
  hykey:
    image: ghcr.io/tricked-dev/hykey:latest
    restart: unless-stopped
    environment:
      - API_KEY=<TOKEN>
      - RUST_LOG=hykey=debug
    networks:
      - redis
    ports:
      - '4000:4000'
networks:
  redis:
    driver: bridge
